src/components/button/Button.js
src/components/button/Button.styles.js
src/components/button/Button.view.js
src/components/index.js
src/screens/dashboard/DashboardScreen.js

Created a button component using default values for title and isDisabled

button: create button with default values

---

src/components/button/Button.js
src/components/button/Button.styles.js
src/components/button/Button.view.js
src/screens/dashboard/DashboardScreen.js

I've added to the existing button component, it will now be able to take `buttonStyle` and `titleStyle` props. This should make it more reusable.

buttonRework: Added more customization options to existing button component

---

src/components/header/Header.js
src/components/header/Header.style.js
src/components/header/Header.view.js
src/components/index.js
src/screens/dashboard/DashboardScreen.js

- Remove complex code
- Use common theme
- Build Header in a separate file

Header: use common styles

---

src/components/button/Button.js
src/components/button/Button.styles.js
src/components/button/Button.view.js
src/components/index.js
src/components/listItem/ListItem.js
src/components/listItem/ListItem.styles.js
src/screens/dashboard/DashboardScreen.js

Everything seems to be working now

DashboardScreen: solved some conflicts and unlinked components

---

src/components/textInput/TextInput.js
src/components/textInput/TextInput.styles.js

I created a new branch with the Text Input Component

TextInput Component

---

package.json
src/components/container/Container.js
src/components/container/Container.styles.js
src/screens/dashboard/DashboardScreen.js
yarn.lock

I created a progress indicator inside `Container.js` for loading while data is being fetched from the back end.

progressIndicator: Added a circular, animated progress indicator

---

package.json
src/components/container/Container.js
src/components/container/Container.styles.js
yarn.lock

I changed the loading indicator to use the built in `ActivityIndicator` rather than the external library version.

progressIndicator: Change to built in ActivityIndicator component

---

src/screens/login/LoginScreen.js
src/screens/login/loginScreen.styles.js

We need to make some changes to the Container so it can accept custom styles

PENDING: Login Screen

---

src/components/stepsProgress/StepsProgress.js
src/components/stepsProgress/StepsProgress.style.js

Added styles with font, color, and size

---

src/components/highlighter/HighLighter.js
src/context/index.js
src/context/quiz/QuizContext.js
src/screens/detail/DetailScreen.js

- Fetch questions according to input from Dashboard Screen
- Created question context
- Render questions according to index
- Move from first question to last question
- Save user answers in array and available in context
- Prepare user answers for Result Screen

Detail Screen Flow: save user answers and prepare them for Result Screen 

---

src/screens/login/LoginScreen.js

Changed login page text input fields to use placeholder text instead of default values

removeTextInputData: Use placeholder text for textinput fields

---

src/navigation/appNavigation/AppNavigation.js

Eliminated the header for navigation/ Simple fix, please approve.

---

src/screens/dashboard/DashboardScreen.js
src/screens/profile/ProfileScreen.js

- Added spinning circle.
- Added profile button.
- Remove sorting data since backend already do it.
- Cleaned up some unused codes.

Michael dulaya/dash board screen cleanup

---

src/screens/profile/ProfileScreen.js

- Initiated profile screen with basic user info. 
- Nick, please improve the styles and modify whatever you feel necessary.

WIP: Nick will take over. Profile Screen: Initiated profile screen. 

---

package.json
src/components/header/Header.js
src/components/header/Header.style.js
yarn.lock

- Refactored Header according to Lasha’s style
- Used Lodash
- Made sure Icons can accept set, name, color and size
- Positioned Icons accordingly, e.g. right icon to right

Header: refactor Header Component

---

src/screens/dashboard/DashboardScreen.js
src/screens/detail/DetailScreen.js
src/screens/profile/ProfileScreen.js
src/screens/result/ResultScreen.js

Replace with new header for:
- Result Screen
- Dashboard Screen
- Detail Screen
- Profile Screen

Header Fix: replace old header with new one

---

src/screens/detail/DetailScreen.js
src/screens/detail/DetailScreen.styles.js
src/screens/detail/DetailScreen.view.js

- NOTE: button will be weird, but will inherit styls from after TextInput is merged
- Created **DetailScreenView** to **decouple** smart and dumb components.
- Used Container's ActivityIndicator.
- Remove unneccessary components
- Use **useEffect** to check if it's at last question, if so submit rightaway (as opposed to haiving another button pop-up asking for submit).
- Created **DetailScreen.styles.js**

DetailScreen Refactor: separate logic from view

---

src/screens/result/ResultScreen.js

Small bug fix allows for accurate score that takes into account the number of questions

ResultScreen: More accurate score based on number of questions

---

src/components/button/Button.styles.js
src/components/textInput/TextInput.styles.js
src/screens/login/LoginScreen.view.js
src/screens/login/loginScreen.styles.js

- Update Button.styles.js
- Update TextInput.styles.js
- Removed Button and TextInput stylings from LoginScreen.view.js since they have the same styling through out the app.

TextInput: fix height for iOS text input.

---

src/screens/result/ResultScreen.js

Moved token request from local storage to global context to ensure token is received before the API call

ResultScreen: axios configuration

---

src/screens/profile/ProfileScreen.js
src/screens/profile/ProfileScreen.styles.js
src/screens/profile/ProfileScreen.view.js

Changed style of ProfileScreen

---

src/configuration/Axios.configuration.js

Notice header was not passed.
```
const profileData = await quizAPI.get('profile');
console.log('profileData: ', profileData.data)
```
```
LOG  profileData:  {"Answers": [], "Email": "First.Last@gmail.com", "Image": "https://react-native-baby-yoda-profile-images.s3.us-west-2.amazonaws.com/26229.jpg", "Name": "First Last", "Scores": ["60%", "45%", "10%", "25%", "35%", "30%", "5%", "0%"]}
```

[Okay to Approve but DON'T Merge] Axios Config: use Axios Interceptors to add token to header
